Third homework
PavelIvut/sber_practice_java pull request #3
Opened 2024-03-25 21:42 UTC by PavelIvut

2024-03-26 10:14 UTC, PavelIvut commented
Почему-то создалась копия коммита третьей домашки.

2024-05-03 13:30 UTC, XLelarX requested changes

2024-05-03 13:30 UTC, XLelarX commented on unit-tests/pom.xml
> +
Модуль unit-tests должен находиться во внешнем модуле, который должен быть прописан здесь и в родительском pom-нике

2024-05-03 13:30 UTC, XLelarX commented on unit-tests/src/main/java/com/test/Colculator.java
> +public class Colculator {
Colculator?)

2024-05-03 13:30 UTC, XLelarX commented on unit-tests/src/test/java/com/test/ClassDTest.java
> +    @Test(expected = RuntimeException.class)
Лучше в следующий раз делай через Assertions.assertThrows, там сами исключения есть еще возможность проанализировать

2024-05-03 13:30 UTC, XLelarX commented on unit-tests/src/test/java/com/test/ColculatorTest.java
> +public class ColculatorTest {
Colculator

2024-05-07 16:57 UTC, merged